// Generated by CoffeeScript 1.4.0
(function() {
  var $, Dffn, Hero, Item, ItemGroup, Skill, SkillBuild, dffn, util;

  $ = window.jQuery;

  util = (function() {

    function util() {}

    util.cleanUp = function() {
      $("#__dffn_container").remove();
      return $("#wrap").show();
    };

    util.addStyles = function() {
      return $("HEAD").append("<link id='__dffn_styles' rel='stylesheet' type='text/css' href='http://dffn.azurewebsites.net/lib/css/dffn.min.css?v=1_3'>");
    };

    util.titleCase = function(str) {
      return str.replace(/\w\S*/g, function(txt) {
        return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
      });
    };

    return util;

  })();

  Item = (function() {

    function Item(name, src) {
      this.name = name;
      this.src = src;
    }

    return Item;

  })();

  ItemGroup = (function() {

    function ItemGroup(name, $items) {
      var item, src;
      this.name = name;
      this.items = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = $items.length; _i < _len; _i++) {
          item = $items[_i];
          name = util.titleCase(item.src.replace(/^.+?\/item\//i, "").replace(/\.png$/i, "").replace(/-/g, " "));
          src = item.src;
          _results.push(new Item(name, src));
        }
        return _results;
      })();
    }

    return ItemGroup;

  })();

  Skill = (function() {

    function Skill(name, level, key, skillImg) {
      this.name = name;
      this.level = level;
      this.key = key;
      this.skillImg = skillImg;
    }

    return Skill;

  })();

  SkillBuild = (function() {

    function SkillBuild($skills) {
      var $sk, key, keyImage, level, name, skill, skillImage;
      this.skills = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = $skills.length; _i < _len; _i++) {
          skill = $skills[_i];
          $sk = $(skill);
          keyImage = $sk.parents("TR").children("TD:last").children("IMG");
          skillImage = $sk.parents("TR").children("TD:first").children("IMG");
          name = $sk.parents("DIV.ajax-tooltip").children("H4").text();
          level = parseInt($sk.text());
          if (name === '') {
            name = "Stats";
          }
          key = "";
          if (keyImage.length > 0) {
            key = keyImage[0].src.replace(/^.+?key-|\.png$/g, "").toUpperCase();
          }
          _results.push(new Skill(name, level, key, skillImage.attr('src')));
        }
        return _results;
      })();
      this.skills.sort(function(a, b) {
        if (a.level >= b.level) {
          return 1;
        } else {
          return -1;
        }
      });
    }

    return SkillBuild;

  })();

  Hero = (function() {

    function Hero(name, url) {
      this.name = name;
      this.url = url;
    }

    return Hero;

  })();

  Dffn = (function() {
    var addBuild, addHeroes;

    function Dffn() {}

    Dffn.prototype.noobify = function() {
      var $dffnContainer, buildName, title;
      util.cleanUp();
      title = $("TITLE").text();
      buildName = $(".build-tab:visible H2").text();
      $dffnContainer = $("      <div id='__dffn_container'>        <a class='__dffn_close'>close</a>        <h1>" + title + "</h1>        <h2>" + buildName + "</h2>        <div id='__dffn_itemgroups'></div>        <div id='__dffn_skills'></div>        <div id='__dffn_heroes'></div>      </div>    ");
      addBuild($dffnContainer);
      addHeroes($dffnContainer);
      $("#wrap").hide();
      return $("BODY").prepend($dffnContainer);
    };

    addBuild = function($container) {
      var $ig, $itemGroups, $skills, item, itemGroup, itemGroups, itemTemplate, key, skill, skillBuild, skillsTemplate, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
      $itemGroups = $("#__dffn_itemgroups", $container);
      $skills = $("#__dffn_skills", $container);
      itemGroups = (function() {
        var _i, _len, _ref, _results;
        _ref = $("DIV.build-tab:visible DIV.items>H4").parent();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          $ig = _ref[_i];
          _results.push(new ItemGroup($("H4", $ig).text(), $("IMG", $ig)));
        }
        return _results;
      })();
      skillBuild = new SkillBuild($("DIV.build-tab:visible DIV.skill-box TD.selected.c"));
      if (itemGroups.length > 0) {
        for (_i = 0, _len = itemGroups.length; _i < _len; _i++) {
          itemGroup = itemGroups[_i];
          itemTemplate = ["<div class='__dffn_itemgroup'><h4>" + itemGroup.name + "</h4><ul>"];
          _ref = itemGroup.items;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            item = _ref[_j];
            itemTemplate.push("<li><img src='" + item.src + "' /> " + item.name + "</li>");
          }
          itemTemplate.push("</ul></div>");
          $itemGroups.append(itemTemplate.join(""));
        }
      } else {
        $itemGroups.remove();
      }
      if (skillBuild.skills.length > 0) {
        skillsTemplate = ["<h4>Hero Skills</h4><ul>"];
        _ref1 = skillBuild.skills;
        for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
          skill = _ref1[_k];
          key = skill.key.length > 0 ? "<span class='__dffn_key'>(" + skill.key + ")</span>" : "";
          skillsTemplate.push("<li><span class='__dffn_level'>" + skill.level + "</span> <img src='" + skill.skillImg + "'/> " + key + " " + skill.name + "</li>");
        }
        skillsTemplate.push("</ul>");
        return $skills.append(skillsTemplate.join(""));
      } else {
        return $skills.remove();
      }
    };

    addHeroes = function($container) {
      var $heroes, hero, heroes, heroesTemplate, link, _i, _len;
      $heroes = $("#__dffn_heroes", $container);
      heroes = (function() {
        var _i, _len, _ref, _results;
        _ref = $("#footer-links .foot-links a.ajax-tooltip");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          link = _ref[_i];
          _results.push(new Hero(link.innerText, link.href));
        }
        return _results;
      })();
      heroes.sort(function(a, b) {
        if (a.name > b.name) {
          return 1;
        } else {
          return -1;
        }
      });
      heroesTemplate = ["<h4>Heroes</h4><ul>"];
      for (_i = 0, _len = heroes.length; _i < _len; _i++) {
        hero = heroes[_i];
        heroesTemplate.push("<li><a href='" + hero.url + "'>" + hero.name + "</a></li>");
      }
      heroesTemplate.push("</ul>");
      return $heroes.append(heroesTemplate.join(""));
    };

    return Dffn;

  })();

  if (!(window.dffn != null)) {
    $("BODY").on("click", ".__dffn_close", function(evt) {
      evt.preventDefault();
      return util.cleanUp();
    });
    util.addStyles();
    dffn = new Dffn();
    dffn.noobify();
    window.dffn = dffn;
  }

}).call(this);
