// Generated by CoffeeScript 1.3.3
(function() {
  var $df4nContainer, $df4nItemGroups, $df4nSkills, $ig, Item, ItemGroup, Skill, SkillBuild, addStyles, buildName, cleanUp, item, itemGroup, itemGroups, key, skill, skillBuild, skillsTemplate, template, title, titleCase, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

  if (!this.df4nLoaded) {
    $("BODY").on("click", ".__df4n_close", function(evt) {
      evt.preventDefault();
      return cleanUp();
    });
    this.df4nLoaded = true;
  }

  cleanUp = function() {
    $("#__df4n_styles, #__df4n_container").remove();
    return $("#wrap").show();
  };

  addStyles = function() {
    return $("HEAD").append("<link id='__df4n_styles' rel='stylesheet' type='text/css' href='http://dffn.azurewebsites.net/static/main/less/df4n.css?v=1_0'>");
  };

  titleCase = function(str) {
    return str.replace(/\w\S*/g, function(txt) {
      return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
  };

  Item = (function() {

    function Item(name, src) {
      this.name = name;
      this.src = src;
    }

    return Item;

  })();

  ItemGroup = (function() {

    function ItemGroup(name, $items) {
      var item, src;
      this.name = name;
      this.items = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = $items.length; _i < _len; _i++) {
          item = $items[_i];
          name = titleCase(item.src.replace(/^.+?\/item\//i, "").replace(/\.png$/i, "").replace(/-/g, " "));
          src = item.src;
          _results.push(new Item(name, src));
        }
        return _results;
      })();
    }

    return ItemGroup;

  })();

  Skill = (function() {

    function Skill(name, level, key, skillImg) {
      this.name = name;
      this.level = level;
      this.key = key;
      this.skillImg = skillImg;
    }

    return Skill;

  })();

  SkillBuild = (function() {

    function SkillBuild($skills) {
      var $sk, key, keyImage, level, name, skill, skillImage;
      this.skills = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = $skills.length; _i < _len; _i++) {
          skill = $skills[_i];
          $sk = $(skill);
          keyImage = $sk.parents("TR").children("TD:last").children("IMG");
          skillImage = $sk.parents("TR").children("TD:first").children("IMG");
          name = $sk.parents("DIV.ajax-tooltip").children("H4").text();
          level = parseInt($sk.text());
          if (name === '') {
            name = "Stats";
          }
          key = "";
          if (keyImage.length > 0) {
            key = keyImage[0].src.replace(/^.+?key-|\.png$/g, "").toUpperCase();
          }
          _results.push(new Skill(name, level, key, skillImage.attr('src')));
        }
        return _results;
      })();
      this.skills.sort(function(a, b) {
        if (a.level >= b.level) {
          return 1;
        } else {
          return -1;
        }
      });
    }

    return SkillBuild;

  })();

  cleanUp();

  addStyles();

  itemGroups = (function() {
    var _i, _len, _ref, _results;
    _ref = $("DIV.build-tab:visible DIV.items>H4").parent();
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      $ig = _ref[_i];
      _results.push(new ItemGroup($("H4", $ig).text(), $("IMG", $ig)));
    }
    return _results;
  })();

  skillBuild = new SkillBuild($("DIV.build-tab:visible DIV.skill-box TD.selected.c"));

  title = $("TITLE").text();

  buildName = $(".build-tab:visible H2").text();

  $df4nContainer = $("  <div id='__df4n_container'>    <a class='__df4n_close'>close</a>    <h1>" + title + "</h1>    <h2>" + buildName + "</h2>    <div id='__df4n_itemgroups'></div>    <div id='__df4n_skills'></div>  </div>");

  $df4nItemGroups = $("#__df4n_itemgroups", $df4nContainer);

  $df4nSkills = $("#__df4n_skills", $df4nContainer);

  for (_i = 0, _len = itemGroups.length; _i < _len; _i++) {
    itemGroup = itemGroups[_i];
    template = [];
    template.push("<div class='__df4n_itemgroup'>");
    template.push("<h4>" + itemGroup.name + "</h4>");
    template.push("<ul>");
    _ref = itemGroup.items;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      item = _ref[_j];
      template.push("<li><img src='" + item.src + "' /> " + item.name + "</li>");
    }
    template.push("</ul>");
    template.push("</div>");
    $df4nItemGroups.append(template.join(""));
  }

  skillsTemplate = [];

  skillsTemplate.push("<h4>Hero Skills</h4>");

  skillsTemplate.push("<ul>");

  _ref1 = skillBuild.skills;
  for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
    skill = _ref1[_k];
    key = "";
    if (skill.key.length > 0) {
      key = "<span class='__df4n_key'>(" + skill.key + "</span>)";
    }
    skillsTemplate.push("<li><span class='__df4n_level'>" + skill.level + "</span> <img src='" + skill.skillImg + "'/> " + key + " " + skill.name + "</li>");
  }

  skillsTemplate.push("</ul>");

  $df4nSkills.append(skillsTemplate.join(""));

  $("BODY").prepend($df4nContainer);

  $("#wrap").hide();

}).call(this);
